In [1]:
#Importando os pacotes
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
#Carregando os dados
dados = pd.read_csv('dadoshistoricos.csv')

In [3]:
#Avaliando o tipo de objeto
type(dados)

pandas.core.frame.DataFrame

In [4]:
#Removendo a columa ID
dados = dados.drop('ID', axis=1)
dados.shape

(76020, 370)

In [5]:
#exibindo os dados
dados.head(10)

   var3  var15  imp_ent_var16_ult1  ...  saldo_medio_var44_ult3          var38  TARGET
0     2     23                 0.0  ...                     0.0   39205.170000       0
1     2     34                 0.0  ...                     0.0   49278.030000       0
2     2     23                 0.0  ...                     0.0   67333.770000       0
3     2     37                 0.0  ...                     0.0   64007.970000       0
4     2     39                 0.0  ...                     0.0  117310.979016       0
5     2     23                 0.0  ...                     0.0   87975.750000       0
6     2     27                 0.0  ...                     0.0   94956.660000       0
7     2     26                 0.0  ...                     0.0  251638.950000       0
8     2     45                 0.0  ...                     0.0  101962.020000       0
9     2     25                 0.0  ...                     0.0  356463.060000       0

[10 rows x 370 columns]

In [6]:
#Separando a variavel TARGET
TARGET = dados[['TARGET']]

In [7]:
#Criando uma lista com as colunas do objeto, deixando a TARGET de fora (já está acima separada)
colunas = dados.columns[0:369].tolist()

In [8]:
#Visualizando a lista com os nomes das colunas
colunas

['var3',
 'var15',
 'imp_ent_var16_ult1',
 'imp_op_var39_comer_ult1',
 'imp_op_var39_comer_ult3',
 'imp_op_var40_comer_ult1',
 'imp_op_var40_comer_ult3',
 'imp_op_var40_efect_ult1',
 'imp_op_var40_efect_ult3',
 'imp_op_var40_ult1',
 'imp_op_var41_comer_ult1',
 'imp_op_var41_comer_ult3',
 'imp_op_var41_efect_ult1',
 'imp_op_var41_efect_ult3',
 'imp_op_var41_ult1',
 'imp_op_var39_efect_ult1',
 'imp_op_var39_efect_ult3',
 'imp_op_var39_ult1',
 'imp_sal_var16_ult1',
 'ind_var1_0',
 'ind_var1',
 'ind_var2_0',
 'ind_var2',
 'ind_var5_0',
 'ind_var5',
 'ind_var6_0',
 'ind_var6',
 'ind_var8_0',
 'ind_var8',
 'ind_var12_0',
 'ind_var12',
 'ind_var13_0',
 'ind_var13_corto_0',
 'ind_var13_corto',
 'ind_var13_largo_0',
 'ind_var13_largo',
 'ind_var13_medio_0',
 'ind_var13_medio',
 'ind_var13',
 'ind_var14_0',
 'ind_var14',
 'ind_var17_0',
 'ind_var17',
 'ind_var18_0',
 'ind_var18',
 'ind_var19',
 'ind_var20_0',
 'ind_var20',
 'ind_var24_0',
 'ind_var24',
 'ind_var25_cte',
 'ind_var26_0',
 'ind_var26_cte',
 'ind_var26',
 'ind_var25_0',
 'ind_var25',
 'ind_var27_0',
 'ind_var28_0',
 'ind_var28',
 'ind_var27',
 'ind_var29_0',
 'ind_var29',
 'ind_var30_0',
 'ind_var30',
 'ind_var31_0',
 'ind_var31',
 'ind_var32_cte',
 'ind_var32_0',
 'ind_var32',
 'ind_var33_0',
 'ind_var33',
 'ind_var34_0',
 'ind_var34',
 'ind_var37_cte',
 'ind_var37_0',
 'ind_var37',
 'ind_var39_0',
 'ind_var40_0',
 'ind_var40',
 'ind_var41_0',
 'ind_var41',
 'ind_var39',
 'ind_var44_0',
 'ind_var44',
 'ind_var46_0',
 'ind_var46',
 'num_var1_0',
 'num_var1',
 'num_var4',
 'num_var5_0',
 'num_var5',
 'num_var6_0',
 'num_var6',
 'num_var8_0',
 'num_var8',
 'num_var12_0',
 'num_var12',
 'num_var13_0',
 'num_var13_corto_0',
 'num_var13_corto',
 'num_var13_largo_0',
 'num_var13_largo',
 'num_var13_medio_0',
 'num_var13_medio',
 'num_var13',
 'num_var14_0',
 'num_var14',
 'num_var17_0',
 'num_var17',
 'num_var18_0',
 'num_var18',
 'num_var20_0',
 'num_var20',
 'num_var24_0',
 'num_var24',
 'num_var26_0',
 'num_var26',
 'num_var25_0',
 'num_var25',
 'num_op_var40_hace2',
 'num_op_var40_hace3',
 'num_op_var40_ult1',
 'num_op_var40_ult3',
 'num_op_var41_hace2',
 'num_op_var41_hace3',
 'num_op_var41_ult1',
 'num_op_var41_ult3',
 'num_op_var39_hace2',
 'num_op_var39_hace3',
 'num_op_var39_ult1',
 'num_op_var39_ult3',
 'num_var27_0',
 'num_var28_0',
 'num_var28',
 'num_var27',
 'num_var29_0',
 'num_var29',
 'num_var30_0',
 'num_var30',
 'num_var31_0',
 'num_var31',
 'num_var32_0',
 'num_var32',
 'num_var33_0',
 'num_var33',
 'num_var34_0',
 'num_var34',
 'num_var35',
 'num_var37_med_ult2',
 'num_var37_0',
 'num_var37',
 'num_var39_0',
 'num_var40_0',
 'num_var40',
 'num_var41_0',
 'num_var41',
 'num_var39',
 'num_var42_0',
 'num_var42',
 'num_var44_0',
 'num_var44',
 'num_var46_0',
 'num_var46',
 'saldo_var1',
 'saldo_var5',
 'saldo_var6',
 'saldo_var8',
 'saldo_var12',
 'saldo_var13_corto',
 'saldo_var13_largo',
 'saldo_var13_medio',
 'saldo_var13',
 'saldo_var14',
 'saldo_var17',
 'saldo_var18',
 'saldo_var20',
 'saldo_var24',
 'saldo_var26',
 'saldo_var25',
 'saldo_var28',
 'saldo_var27',
 'saldo_var29',
 'saldo_var30',
 'saldo_var31',
 'saldo_var32',
 'saldo_var33',
 'saldo_var34',
 'saldo_var37',
 'saldo_var40',
 'saldo_var41',
 'saldo_var42',
 'saldo_var44',
 'saldo_var46',
 'var36',
 'delta_imp_amort_var18_1y3',
 'delta_imp_amort_var34_1y3',
 'delta_imp_aport_var13_1y3',
 'delta_imp_aport_var17_1y3',
 'delta_imp_aport_var33_1y3',
 'delta_imp_compra_var44_1y3',
 'delta_imp_reemb_var13_1y3',
 'delta_imp_reemb_var17_1y3',
 'delta_imp_reemb_var33_1y3',
 'delta_imp_trasp_var17_in_1y3',
 'delta_imp_trasp_var17_out_1y3',
 'delta_imp_trasp_var33_in_1y3',
 'delta_imp_trasp_var33_out_1y3',
 'delta_imp_venta_var44_1y3',
 'delta_num_aport_var13_1y3',
 'delta_num_aport_var17_1y3',
 'delta_num_aport_var33_1y3',
 'delta_num_compra_var44_1y3',
 'delta_num_reemb_var13_1y3',
 'delta_num_reemb_var17_1y3',
 'delta_num_reemb_var33_1y3',
 'delta_num_trasp_var17_in_1y3',
 'delta_num_trasp_var17_out_1y3',
 'delta_num_trasp_var33_in_1y3',
 'delta_num_trasp_var33_out_1y3',
 'delta_num_venta_var44_1y3',
 'imp_amort_var18_hace3',
 'imp_amort_var18_ult1',
 'imp_amort_var34_hace3',
 'imp_amort_var34_ult1',
 'imp_aport_var13_hace3',
 'imp_aport_var13_ult1',
 'imp_aport_var17_hace3',
 'imp_aport_var17_ult1',
 'imp_aport_var33_hace3',
 'imp_aport_var33_ult1',
 'imp_var7_emit_ult1',
 'imp_var7_recib_ult1',
 'imp_compra_var44_hace3',
 'imp_compra_var44_ult1',
 'imp_reemb_var13_hace3',
 'imp_reemb_var13_ult1',
 'imp_reemb_var17_hace3',
 'imp_reemb_var17_ult1',
 'imp_reemb_var33_hace3',
 'imp_reemb_var33_ult1',
 'imp_var43_emit_ult1',
 'imp_trans_var37_ult1',
 'imp_trasp_var17_in_hace3',
 'imp_trasp_var17_in_ult1',
 'imp_trasp_var17_out_hace3',
 'imp_trasp_var17_out_ult1',
 'imp_trasp_var33_in_hace3',
 'imp_trasp_var33_in_ult1',
 'imp_trasp_var33_out_hace3',
 'imp_trasp_var33_out_ult1',
 'imp_venta_var44_hace3',
 'imp_venta_var44_ult1',
 'ind_var7_emit_ult1',
 'ind_var7_recib_ult1',
 'ind_var10_ult1',
 'ind_var10cte_ult1',
 'ind_var9_cte_ult1',
 'ind_var9_ult1',
 'ind_var43_emit_ult1',
 'ind_var43_recib_ult1',
 'var21',
 'num_var2_0_ult1',
 'num_var2_ult1',
 'num_aport_var13_hace3',
 'num_aport_var13_ult1',
 'num_aport_var17_hace3',
 'num_aport_var17_ult1',
 'num_aport_var33_hace3',
 'num_aport_var33_ult1',
 'num_var7_emit_ult1',
 'num_var7_recib_ult1',
 'num_compra_var44_hace3',
 'num_compra_var44_ult1',
 'num_ent_var16_ult1',
 'num_var22_hace2',
 'num_var22_hace3',
 'num_var22_ult1',
 'num_var22_ult3',
 'num_med_var22_ult3',
 'num_med_var45_ult3',
 'num_meses_var5_ult3',
 'num_meses_var8_ult3',
 'num_meses_var12_ult3',
 'num_meses_var13_corto_ult3',
 'num_meses_var13_largo_ult3',
 'num_meses_var13_medio_ult3',
 'num_meses_var17_ult3',
 'num_meses_var29_ult3',
 'num_meses_var33_ult3',
 'num_meses_var39_vig_ult3',
 'num_meses_var44_ult3',
 'num_op_var39_comer_ult1',
 'num_op_var39_comer_ult3',
 'num_op_var40_comer_ult1',
 'num_op_var40_comer_ult3',
 'num_op_var40_efect_ult1',
 'num_op_var40_efect_ult3',
 'num_op_var41_comer_ult1',
 'num_op_var41_comer_ult3',
 'num_op_var41_efect_ult1',
 'num_op_var41_efect_ult3',
 'num_op_var39_efect_ult1',
 'num_op_var39_efect_ult3',
 'num_reemb_var13_hace3',
 'num_reemb_var13_ult1',
 'num_reemb_var17_hace3',
 'num_reemb_var17_ult1',
 'num_reemb_var33_hace3',
 'num_reemb_var33_ult1',
 'num_sal_var16_ult1',
 'num_var43_emit_ult1',
 'num_var43_recib_ult1',
 'num_trasp_var11_ult1',
 'num_trasp_var17_in_hace3',
 'num_trasp_var17_in_ult1',
 'num_trasp_var17_out_hace3',
 'num_trasp_var17_out_ult1',
 'num_trasp_var33_in_hace3',
 'num_trasp_var33_in_ult1',
 'num_trasp_var33_out_hace3',
 'num_trasp_var33_out_ult1',
 'num_venta_var44_hace3',
 'num_venta_var44_ult1',
 'num_var45_hace2',
 'num_var45_hace3',
 'num_var45_ult1',
 'num_var45_ult3',
 'saldo_var2_ult1',
 'saldo_medio_var5_hace2',
 'saldo_medio_var5_hace3',
 'saldo_medio_var5_ult1',
 'saldo_medio_var5_ult3',
 'saldo_medio_var8_hace2',
 'saldo_medio_var8_hace3',
 'saldo_medio_var8_ult1',
 'saldo_medio_var8_ult3',
 'saldo_medio_var12_hace2',
 'saldo_medio_var12_hace3',
 'saldo_medio_var12_ult1',
 'saldo_medio_var12_ult3',
 'saldo_medio_var13_corto_hace2',
 'saldo_medio_var13_corto_hace3',
 'saldo_medio_var13_corto_ult1',
 'saldo_medio_var13_corto_ult3',
 'saldo_medio_var13_largo_hace2',
 'saldo_medio_var13_largo_hace3',
 'saldo_medio_var13_largo_ult1',
 'saldo_medio_var13_largo_ult3',
 'saldo_medio_var13_medio_hace2',
 'saldo_medio_var13_medio_hace3',
 'saldo_medio_var13_medio_ult1',
 'saldo_medio_var13_medio_ult3',
 'saldo_medio_var17_hace2',
 'saldo_medio_var17_hace3',
 'saldo_medio_var17_ult1',
 'saldo_medio_var17_ult3',
 'saldo_medio_var29_hace2',
 'saldo_medio_var29_hace3',
 'saldo_medio_var29_ult1',
 'saldo_medio_var29_ult3',
 'saldo_medio_var33_hace2',
 'saldo_medio_var33_hace3',
 'saldo_medio_var33_ult1',
 'saldo_medio_var33_ult3',
 'saldo_medio_var44_hace2',
 'saldo_medio_var44_hace3',
 'saldo_medio_var44_ult1',
 'saldo_medio_var44_ult3',
 'var38']

In [9]:
#Criando um array dos dados
array = dados.values

In [10]:
#Visualizando o tipo do objeto
type(array)

numpy.ndarray

In [11]:
#Separando o array em componentes do input (x) da variavel TARGET
X = array[:,0:369]

#Gerando a nova ecala (normalizando os dados)
scaler = MinMaxScaler(feature_range = (0, 1))
rescaledX = scaler.fit_transform(X)

In [12]:
#Transformando o Array em Dataframe
dadosNormalizados = pd.DataFrame(rescaledX, columns = colunas)

In [13]:
#Visualizando o formato do dataframe
dadosNormalizados.shape

(76020, 369)

In [14]:
#Reduzindo a dimensionalidade
pca = PCA(n_components = 30)
dados = pca.fit_transform(dadosNormalizados)

In [15]:
#Convertendo o objeto PCA para um dataframe
dados = pd.DataFrame(dados)

In [16]:
dados.head()

         0         1         2         3   ...        26        27        28        29
0 -1.274542 -0.375972  0.056829  0.439875  ...  0.005148  0.003657  0.007141 -0.001370
1 -0.108038  0.048862  1.799190 -0.203618  ... -0.047619 -0.008906  0.002499 -0.061272
2  0.027935  0.439468 -0.335930  0.187874  ... -0.029984 -0.005791 -0.002757  0.001031
3  1.427146 -1.492291 -0.688243 -0.024221  ...  0.002226  0.009852  0.023860  0.053124
4  0.426464 -0.122872  1.311621 -0.190963  ... -0.123019 -0.030567 -0.023965 -0.146107

[5 rows x 30 columns]

In [17]:
#Concatetando a variavel TARGET ao DataFrame
dados = pd.concat([dados, TARGET], axis=1)

In [18]:
#Visualizando os dados
dados

              0         1         2         3  ...        27        28        29  TARGET
0     -1.274542 -0.375972  0.056829  0.439875  ...  0.003657  0.007141 -0.001370       0
1     -0.108038  0.048862  1.799190 -0.203618  ... -0.008906  0.002499 -0.061272       0
2      0.027935  0.439468 -0.335930  0.187874  ... -0.005791 -0.002757  0.001031       0
3      1.427146 -1.492291 -0.688243 -0.024221  ...  0.009852  0.023860  0.053124       0
4      0.426464 -0.122872  1.311621 -0.190963  ... -0.030567 -0.023965 -0.146107       0
...         ...       ...       ...       ...  ...       ...       ...       ...     ...
76015 -1.270342 -0.384579  0.077956  0.434298  ...  0.005429 -0.011165 -0.010873       0
76016 -0.067651 -0.107534  1.304143 -0.150065  ... -0.023916  0.008731  0.058832       0
76017 -0.106216  0.347587 -0.295098  0.193288  ... -0.004840  0.007015  0.002311       0
76018  0.048572  0.431814 -0.295902  0.319859  ... -0.000675 -0.002458 -0.004372       0
76019 -1.270678 -0.383891  0.076267  0.434744  ...  0.005287 -0.009701 -0.010115       0

[76020 rows x 31 columns]

In [19]:
#Dados de treino e de teste
dados_treino = dados.sample(frac=0.60, random_state=0)
dados_teste = dados.drop(dados_treino.index)

In [20]:
#Gerando as variaveis preditoras e variavel TARGET
x_treino = dados_treino.iloc[:,0:30]
y_treino = dados_treino.iloc[:,30:31]

x_teste = dados_teste.iloc[:,0:30]
y_teste = dados_teste.iloc[:,30:31]

In [21]:
#Contagem dos dados
dados_treino.count()

0         45612
1         45612
2         45612
3         45612
4         45612
5         45612
6         45612
7         45612
8         45612
9         45612
10        45612
11        45612
12        45612
13        45612
14        45612
15        45612
16        45612
17        45612
18        45612
19        45612
20        45612
21        45612
22        45612
23        45612
24        45612
25        45612
26        45612
27        45612
28        45612
29        45612
TARGET    45612
dtype: int64

In [22]:
#Contagem dos dados
dados_teste.count()

0         30408
1         30408
2         30408
3         30408
4         30408
5         30408
6         30408
7         30408
8         30408
9         30408
10        30408
11        30408
12        30408
13        30408
14        30408
15        30408
16        30408
17        30408
18        30408
19        30408
20        30408
21        30408
22        30408
23        30408
24        30408
25        30408
26        30408
27        30408
28        30408
29        30408
TARGET    30408
dtype: int64

In [23]:
#Classificador Random Forest
classificador = RandomForestClassifier(max_depth=5, random_state=0)
classificador.fit(x_treino, y_treino)

#Executando as previsões
previsoes = classificador.predict(x_teste)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [25]:
#Avaliando o Confusion matrix e a acuracia
#Resultado é que a cada 100x, o modelo vai acertar 96%
print('Acuracia: %s' % accuracy_score(y_teste, previsoes))

Acuracia: 0.9607340173638517